=== 0b5vr/livecode.demozoo.org/meta/event.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "file://./meta/event.schema.json",
  "title": "Event",
  "description": "An event which consist of a set of phases",
  "type": "object",
  "properties": {
    "title": {
      "description": "Name of the Event",
      "type": "string"
    },
    "started": {
      "description": "First day of the event, ISO-8601 format",
      "type": "string"
    },
    "date": {
      "description": "Human readable date",
      "type": "string"
    },
    "type": {
      "description": "Type of event",
      "type": "string"
    },
    "vod": {
      "description": "Link if VOD",
      "type": ["string", "null"]
    },
    "software_used": {
      "description": "Sofware used",
      "type": ["string", "null"]
    },
    "phases": {
      "title": "Phases",
      "description": "All the phases of the event",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Phase",
        "description": "A phase of the event. Consists of multiple entries",
        "properties": {
          "title": {
            "description": "Phase title. Can be null if the event is one phase e.g",
            "type": ["string", "null"]
          },
          "vod": {
            "description": "Link if VOD",
            "type": ["string", "null"]
          },
          "entries": {
            "title": "Entries",
            "description": "All the entry of the phase",
            "type": "array",
            "items": {
              "type": "object",
              "title": "Entry",
              "description": "An entry. Which here consists of a shader creation",
              "properties": {
                "id": {
                  "description": "User Id for the phase (usually for Shader Royale)",
                  "type": ["string", "null"]
                },
                "rank": {
                  "description": "Rank of the entry",
                  "type": ["integer", "null"]
                },
                "points": {
                  "description": "Points of the entry",
                  "type": ["integer", "null"]
                },
                "handle": {
                  "description": "Handle / Username",
                  "type": ["string"]
                },
                "shader_file": {
                  "description": "File of the entry",
                  "type": ["string", "null"]
                },
                "shadertoy_url": {
                  "description": "Shadertoy url",
                  "type": ["string", "null"]
                },
                "vod": {
                  "description": "Link if VOD",
                  "type": ["string", "null"]
                }
              },
              "required": ["handle"]
            }
          },
          "staffs": {
            "description": "Staff info for the phase",
            "type": "array",
            "items": {
              "type": "object",
              "title": "Staff",
              "description": "Staff information. What people were doing",
              "properties": {
                "job": {
                  "description": "Job",
                  "type": "string",
                  "enum": ["Live Music", "Dj Set", "Commentators"]
                },
                "handle": {
                  "description": "Handle / Username",
                  "type": "string"
                }
              },
              "required": ["job", "handle"]
            }
          }
        }
      }
    },
    "staffs": {
      "description": "Staff info for the whole Event",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Staff",
        "description": "Staff information. What people were doing",
        "properties": {
          "job": {
            "description": "Job",
            "type": "string",
            "enum": ["Organizers"]
          },
          "handle": {
            "description": "Handle / Username",
            "type": "string"
          }
        },
        "required": ["job", "handle"]
      }
    }
  },
  "required": ["title", "started", "date", "type"]
}

=== 0b5vr/livecode.demozoo.org/data/2021_shader_challenge.json
{
  "title": "Shader Chaλλenge 2021",
  "started": "2021-02-27",
  "date": "27 Feb 2021",
  "type": "Shader Challenge",
  "vod": "https://www.youtube.com/watch?v=2NJrpOFxSSo",
  "software_used": null,
  "phases": [
    {
      "title": null,
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "FMS_Cat",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/tlyBWw"
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "butadiene",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/wtGfWw"
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "sp4ghet",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "らくとあいす (lactoice)",
          "job": "Live Music"
        },
        {
          "handle": "わたし (phi16)",
          "job": "Commentators"
        }
      ]
    }
  ],
  "staffs": [
    {
	"handle": "わたし (phi16)",
	"job": "Organizers"
    }
  ]
}

=== 0b5vr/livecode.demozoo.org/data/2020_shader_showdown_assembly.json
{
  "title": "Assembly Autumn Online",
  "started": "2020-10-14",
  "date": "14 - 18 Oct 2020",
  "type": "Shader Showdown",
  "vod": null,
  "software_used": null,
  "phases": [
    {
      "title": "Semifinal 1",
      "vod": "https://www.youtube.com/watch?v=UV7JBHUckiY",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": 196,
          "handle": "Exca",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": 178,
          "handle": "Provod",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": "https://www.youtube.com/watch?v=MH7NuNXrxt0"
        }
      ],
      "staffs": [
        {
          "handle": "eimink",
          "job": "Dj Set"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Semifinal 2",
      "vod": "https://youtu.be/UV7JBHUckiY?t=2040",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": 336,
          "handle": "monsieursoleil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": 323,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "eimink",
          "job": "Dj Set"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Final",
      "vod": "https://www.youtube.com/watch?v=MrN4-JC88ME",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": 469,
          "handle": "monsieursoleil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": 421,
          "handle": "Exca",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/WsGyDW"
        }
      ],
      "staffs": [
        {
          "handle": "mayor",
          "job": "Dj Set"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        }
      ]
    }
  ],
  "staffs": []
}

=== 0b5vr/livecode.demozoo.org/data/2020_shader_jam_assembly_summer.json
{
  "title": "Assembly Summer Online",
  "started": "2020-08-08",
  "date": "6 Dec 2020",
  "type": "Shader Jam",
  "vod": null,
  "software_used": null,
  "phases": [
    {
      "title": "Round 1",
      "vod": "https://www.youtube.com/watch?v=m7b1lIHiZc8",
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "branch",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "lamogui",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "Exca",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/3tsBD7"
        }
      ],
      "staffs": [
        {
          "handle": "eimink",
          "job": "Dj Set"
        }
      ]
    },
    {
      "title": "Round 2",
      "vod": "https://www.youtube.com/watch?v=3-jwyYfI7Q8",
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "visy",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "Leon Denise",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "mayor",
          "job": "Dj Set"
        }
      ]
    }
  ],
  "staffs": []
}

=== 0b5vr/livecode.demozoo.org/data/2018_shader_showdown_vip.json
{
  "title": "Very Important Party",
  "started": "2018-06-01",
  "date": "1 - 3 Jun 2018",
  "type": "Shader Showdown",
  "vod": null,
  "software_used": [{
		"name": "Bonzomatic",
		"url": "https://github.com/TheNuSan/Bonzomatic/releases/tag/v11",
		"version": "NuSan - v11",
		"purpose": "Graphic"
	  	}],
  "phases": [
    {
      "title": "Qualification #1",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "ponk",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/01-ponk.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/01-ponk.jpg"
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "xtrium",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/01-xtrium.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/01-xtrium.jpg"
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Qualification #2",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "CoyHot",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/02-coyhot.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/02-coyhot.jpg"
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "lamogui",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/02-lamogui.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/02-lamogui.jpg"
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Semi #1",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "ponk",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/03-ponk.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/03-ponk.jpg"
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "Flopine",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/03-flopine.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/03-flopine.jpg"
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Semi #2",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "lsdlive",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/04-lsdlive.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/04-lsdlive.jpg"
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "CoyHot",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/04-coyhot.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/04-coyhot.jpg"
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Little Final",
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "CoyHot",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/05-coyhot.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/05-coyhot.jpg"
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "ponk",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/05-ponk.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/05-ponk.jpg"
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Great Final",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "Flopine",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/06_flopine.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/06_flopine.jpg"
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "lsdlive",
          "shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-06-02/06-lsdlive.glsl",
          "shadertoy_url": null,
          "preview_image": "vip_2018-06-02/06-lsdlive.jpg"
        }
      ],
      "staffs": [
      ]
    }
  ],
  "staffs": [{
    "handle": "Cookie Collective",
    "job": "Organizers"
  }
  ]
}

=== 0b5vr/livecode.demozoo.org/data/2021_shader_showdown_outline_online.json
{
  "title": "Outline Online 2021",
  "started": "2021-05-13",
  "date": "13 - 16 May 2021",
  "type": "Shader Showdown",
  "vod": null,
  "software_used": [
    {
      "name": "Bonzomatic",
      "url": "https://github.com/TheNuSan/Bonzomatic/releases/tag/v11",
      "version": "NuSan - v11",
      "purpose": "Graphic"
    }
  ],
  "phases": [
    {
      "title": "Group 1 - Match 1",
      "vod": null,
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "anticore",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/ssjSDV"
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "MrSoleil",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Group 2 - Match 1",
      "vod": null,
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "totetmatt",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "blackle",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Group 1 - Match 2",
      "vod": null,
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "MonsieurSoleil",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Group 2 - Match 2",
      "vod": null,
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "cosamentale",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/fs2XWc"
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "totetmatt",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Group 1 - Match 3",
      "vod": null,
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "anticore",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Group 2 - Match 3",
      "vod": null,
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "blackle",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "cosamentale",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/NsSXWd"
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Final",
      "vod": null,
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/sdBSDt"
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "cosamentale",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
       
      ]
    },
    {
      "title": "Shaderjam 1",
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "exca",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "lechugafeliz",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "rimina",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "LynnDrum",
          "job": "Dj Set"
        }
      ]
    }
  ],
  "staffs": []
}

=== 0b5vr/livecode.demozoo.org/data/2020_shader_royale_inercia.json
{
  "title": "In√©rcia 2020",
  "started": "2020-10-02",
  "date": "2 - 3 Oct 2020",
  "type": "Shader Royale",
  "vod": "https://www.youtube.com/watch?v=08Ll9OkMmOI",
  "software_used": null,
  "phases": [
    {
      "title": null,
      "entries": [
        {
          "id": "04",
          "rank": 1,
          "points": 141,
          "handle": "NuSan",
          "shader_file": "./shader_file_sources/shader_royale_1/grabber_inerciaroyale_nusan.glsl",
          "shadertoy_url": null,
          "preview_image" : "shader_royale_1/grabber_inerciaroyale_nusan.jpg"
        },
        {
          "id": "06",
          "rank": 2,
          "points": 140,
          "handle": "FMS_Cat",
          "shader_file": "./shader_file_sources/shader_royale_1/grabber_inerciaroyale_FMS_Cat.glsl",
          "shadertoy_url": null,
          "preview_image" : "shader_royale_1/grabber_inerciaroyale_FMS_Cat.jpg"
        },
        {
          "id": "01",
          "rank": 3,
          "points": 99,
          "handle": "wrighter",
          "shader_file": "./shader_file_sources/shader_royale_1/grabber_inerciaroyale_wrighter.glsl",
          "shadertoy_url": null,
          "preview_image" : "shader_royale_1/grabber_inerciaroyale_wrighter.jpg"
        },
        {
          "id": "08",
          "rank": 4,
          "points": 94,
          "handle": "evvvvil",
          "shader_file": "./shader_file_sources/shader_royale_1/grabber_inerciaroyale_evvvvil.glsl",
          "shadertoy_url": null,
          "preview_image" : "shader_royale_1/grabber_inerciaroyale_evvvvil.jpg"
        },
        {
          "id": "05",
          "rank": 5,
          "points": 73,
          "handle": "LechugaFeliz",
          "shader_file": "./shader_file_sources/shader_royale_1/grabber_inerciaroyale_LechugaFeliz.glsl",
          "shadertoy_url": null,
          "preview_image" : "shader_royale_1/grabber_inerciaroyale_LechugaFeliz.jpg"
        },
        {
          "id": "07",
          "rank": 6,
          "points": 71,
          "handle": "fizzer",
          "shader_file": "./shader_file_sources/shader_royale_1/grabber_inerciaroyale_fizzer.glsl",
          "shadertoy_url": null,
          "preview_image" : "shader_royale_1/grabber_inerciaroyale_fizzer.jpg"
        },
        {
          "id": "02",
          "rank": 7,
          "points": 70,
          "handle": "rimina",
          "shader_file": "./shader_file_sources/shader_royale_1/grabber_inerciaroyale_rimina.glsl",
          "shadertoy_url": null,
          "preview_image" : "shader_royale_1/grabber_inerciaroyale_rimina.jpg"
        },
        {
          "id": "03",
          "rank": 8,
          "points": 56,
          "handle": "provod",
          "shader_file": "./shader_file_sources/shader_royale_1/grabber_inerciaroyale_provod.glsl",
          "shadertoy_url": null,
          "preview_image" : "shader_royale_1/grabber_inerciaroyale_provod.jpg"
        },
        {
          "id": "09",
          "rank": 9,
          "points": 11,
          "handle": "blackle",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "lug00ber",
          "job": "Dj Set"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        }
      ]
    }
  ],
  "staffs": [
    {
      "handle": "ps",
      "job": "Organizers"
    },
    {
      "handle": "alien01",
      "job": "Organizers"
    }
  ]
}

=== 0b5vr/livecode.demozoo.org/data/2018_shader_showdown_outline.json
{
  "title": "Outline",
  "started": "2018-05-10",
  "date": "10 - 13 May 2020",
  "type": "Shader Showdown",
  "vod": null,
  "software_used": null,
  "phases": [
    {
      "title": "Semifinal #1",
      "vod": "https://www.youtube.com/watch?v=q8iFI1-v5n8",
      "entries": [
        {
          "id": 1,
          "rank": 1,
          "points": null,
          "handle": "lsdlive",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": 2,
          "rank": 2,
          "points": null,
          "handle": "TropicalTrevor",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "dojoe",
          "job": "Dj Set"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "andro",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Semifinals #2",
      "vod": "https://youtu.be/q8iFI1-v5n8?t=1618",
      "entries": [
        {
          "id": 1,
          "rank": 2,
          "points": null,
          "handle": "lj",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": 2,
          "rank": 1,
          "points": null,
          "handle": "Flopine",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "dojoe",
          "job": "Dj Set"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "andro",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Final",
      "vod": "https://youtu.be/q8iFI1-v5n8?t=3344",
      "entries": [
        {
          "id": 1,
          "rank": 1,
          "points": null,
          "handle": "lsdlive",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": 2,
          "rank": 2,
          "points": null,
          "handle": "Flopine",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "dojoe",
          "job": "Dj Set"
        },
        {
          "handle": "klandox",
          "job": "Commentators"
        },
        {
          "handle": "andro",
          "job": "Commentators"
        }
      ]
    }
  ],
  "staffs": [
        {
          "handle": "havoc",
          "job": "Organizers"
        }
  ]
}
