=== 0b5vr/livecode.demozoo.org/meta/event.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "file://./meta/event.schema.json",
  "title": "Event",
  "description": "An event which consist of a set of phases",
  "type": "object",
  "properties": {
    "title": {
      "description": "Name of the Event",
      "type": "string"
    },
    "started": {
      "description": "First day of the event, ISO-8601 format",
      "type": "string"
    },
    "date": {
      "description": "Human readable date",
      "type": "string"
    },
    "type": {
      "description": "Type of event",
      "type": "string"
    },
    "vod": {
      "description": "Link if VOD",
      "type": ["string", "null"]
    },
    "software_used": {
      "description": "Sofware used",
      "type": ["string", "null"]
    },
    "phases": {
      "title": "Phases",
      "description": "All the phases of the event",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Phase",
        "description": "A phase of the event. Consists of multiple entries",
        "properties": {
          "title": {
            "description": "Phase title. Can be null if the event is one phase e.g",
            "type": ["string", "null"]
          },
          "vod": {
            "description": "Link if VOD",
            "type": ["string", "null"]
          },
          "entries": {
            "title": "Entries",
            "description": "All the entry of the phase",
            "type": "array",
            "items": {
              "type": "object",
              "title": "Entry",
              "description": "An entry. Which here consists of a shader creation",
              "properties": {
                "id": {
                  "description": "User Id for the phase (usually for Shader Royale)",
                  "type": ["string", "null"]
                },
                "rank": {
                  "description": "Rank of the entry",
                  "type": ["integer", "null"]
                },
                "points": {
                  "description": "Points of the entry",
                  "type": ["integer", "null"]
                },
                "handle": {
                  "description": "Handle / Username",
                  "type": ["string"]
                },
                "shader_file": {
                  "description": "File of the entry",
                  "type": ["string", "null"]
                },
                "shadertoy_url": {
                  "description": "Shadertoy url",
                  "type": ["string", "null"]
                },
                "vod": {
                  "description": "Link if VOD",
                  "type": ["string", "null"]
                }
              },
              "required": ["handle"]
            }
          },
          "staffs": {
            "description": "Staff info for the phase",
            "type": "array",
            "items": {
              "type": "object",
              "title": "Staff",
              "description": "Staff information. What people were doing",
              "properties": {
                "job": {
                  "description": "Job",
                  "type": "string",
                  "enum": ["Live Music", "Dj Set", "Commentators"]
                },
                "handle": {
                  "description": "Handle / Username",
                  "type": "string"
                }
              },
              "required": ["job", "handle"]
            }
          }
        }
      }
    },
    "staffs": {
      "description": "Staff info for the whole Event",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Staff",
        "description": "Staff information. What people were doing",
        "properties": {
          "job": {
            "description": "Job",
            "type": "string",
            "enum": ["Organizers"]
          },
          "handle": {
            "description": "Handle / Username",
            "type": "string"
          }
        },
        "required": ["job", "handle"]
      }
    }
  },
  "required": ["title", "started", "date", "type"]
}

=== 0b5vr/livecode.demozoo.org/data/2020_shader_royale_shader_royale2.json
{
  "title": "Shader Royale #2",
  "started": "2020-12-04",
  "date": "4 Dec 2020",
  "type": "Shader Royale",
  "vod": "https://www.youtube.com/watch?v=wwN5vRXKAl8",
  "software_used": null,
  "phases": [
    {
      "title": null,
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": 333,
          "handle": "FMS_Cat",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": 326,
          "handle": "cosamentale",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 3,
          "points": 279,
          "handle": "NuSan",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 4,
          "points": 221,
          "handle": "monsieursoleil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 5,
          "points": 208,
          "handle": "anticore",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 6,
          "points": 154,
          "handle": "LechugaFeliz",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 7,
          "points": 151,
          "handle": "branch",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 8,
          "points": 150,
          "handle": "dok",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 9,
          "points": 150,
          "handle": "visy",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 10,
          "points": 149,
          "handle": "wrighter",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 11,
          "points": 131,
          "handle": "provod",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 12,
          "points": 130,
          "handle": "Exca",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 13,
          "points": 103,
          "handle": "NR4",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "lug00ber",
          "job": "Dj Set"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        }
      ]
    }
  ],
  "staffs": [
    {
      "handle": "ps",
      "job": "Organizers"
    },
    {
      "handle": "alien01",
      "job": "Organizers"
    }
  ]
}

=== 0b5vr/livecode.demozoo.org/data/2018_shader_showdown_demosplash.json
{
  "title": "Demosplash",
  "started": "2018-11-02",
  "date": "2 Nov 2018",
  "type": "Shader Showdown",
  "vod": null,
  "software_used": null,
  "phases": [
    {
      "title": "Live Shader",
      "vod": null,
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": 185,
          "handle": "CharStiles",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": 159,
          "handle": "lsh",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": []
    }
  ],
  "staffs": []
}

=== 0b5vr/livecode.demozoo.org/data/2019_shader_showdown_woot_devices.json
{
	"title": "Woot Devices 4",
	"started": "2019-05-04",
	"date": "4 May 2019",
	"type": "Shader Showdown",
	"vod": null,
	"software_used": [
        {
			"name": "Veda",
			"url": "https://veda.gl/",
			"version": "",
			"purpose": "Graphic"
		}
      ],
	"phases": [{
			"title": "",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2019-05-04/elie1.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2019-05-04/elie2.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2019-05-04/elie3.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2019-05-04/elie4.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2019-05-04/elie5.frag",
					"shadertoy_url": null
				}
			],
			"staffs": [
			]
		}
	],
	"staffs": [{
			"handle": "Cookie Collective",
			"job": "Organizers"
		}
	]
}

=== 0b5vr/livecode.demozoo.org/data/revision_online_2021.json
{
  "title": "Revision Online 2021",
  "started": "2021-04-02",
  "date": "2-5 April 2021",
  "type": "Shader Showdown",
  "vod": null,
  "software_used": "https://github.com/TheNuSan/Bonzomatic/releases/tag/v11",
  "phases": [
    {
      "title": "Quarter Final 1",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "anticore",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "LechugaFelix",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "ronny",
          "job": "Dj Set"
        },
        {
          "handle": "Diffty",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "blackle",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Quarter Final 2",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "blackle",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "cosamentale",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "h0ffman",
          "job": "Dj Set"
        },
        {
          "handle": "Diffty",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "flopine",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Quarter Final 3",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "monsieursoleil",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "ronny",
          "job": "Dj Set"
        },
        {
          "handle": "Diffty",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "blackle",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Quarter Final 4",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "flopine",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "wrighter",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "ronny",
          "job": "Dj Set"
        },
        {
          "handle": "Diffty",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "blackle",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Semi Final 1",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "blackle",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "anticore",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "ronny",
          "job": "Dj Set"
        },
        {
          "handle": "Diffty",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "flopine",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Semi Final 2",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "flopine",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "ronny",
          "job": "Dj Set"
        },
        {
          "handle": "Diffty",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "blackle",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Final",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "blackle",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "alkama",
          "job": "Dj Set"
        },
        {
          "handle": "Diffty",
          "job": "Commentators"
        },
        {
          "handle": "ps",
          "job": "Commentators"
        },
        {
          "handle": "okkie",
          "job": "Commentators"
        },
        {
          "handle": "wrighter",
          "job": "Commentators"
        },
        {
          "handle": "flopine",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Shaderjam 1",
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "nusan",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "lechugafeliz",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "eimink",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/fsjGDD"
        }
      ],
      "staffs": [
        {
          "handle": "LynnDrum",
          "job": "Dj Set"
        }
      ]
    },
    {
      "title": "Shaderjam 2",
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "plek",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "sp4ghet",
          "shader_file": null,
          "shadertoy_url": "https://www.shadertoy.com/view/Ndj3Wm"
        }
      ],
      "staffs": [
        {
          "handle": "messy",
          "job": "Dj Set"
        }
      ]
    },
    {
      "title": "Shaderjam 3",
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "exca",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "rimina",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "visy",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "ghost",
          "job": "Dj Set"
        }
      ]
    }
  ],
  "staffs": []
}

=== 0b5vr/livecode.demozoo.org/data/2021_byte_battle_outline_online.json
{
  "title": "Outline Online 2021",
  "started": "2021-05-13",
  "date": "13 - 16 May 2021",
  "type": "Byte Battle",
  "vod": null,
  "software_used": [
    {
      "name": "TIC-80",
      "url": "https://tic80.com/",
      "version": "0.80",
      "purpose": "Graphic"
    }
  ],
  "phases": [
    {
      "title": "Quarter #1",
      "vod": "https://www.youtube.com/watch?v=uYBZ8pRWwgo",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "aldroid",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "ps",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Quarter #2",
      "vod": "https://youtu.be/uYBZ8pRWwgo?t=1930",
      "entries": [
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "killedbyapixel",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "exoticorn",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Quart #3",
      "vod": "https://youtu.be/uYBZ8pRWwgo?t=3798",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "gopher",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "tomcat",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Quart #4",
      "vod": "https://youtu.be/uYBZ8pRWwgo?t=5699",
      "entries": [
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "popolon",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "FMS_cat",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Semi #1",
      "vod": "https://www.youtube.com/watch?v=KIv5N-nV_vQ",
      "entries": [
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "aldroid",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "exoticorn",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Semi #2",
      "vod": "https://youtu.be/KIv5N-nV_vQ?t=1915",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "gopher",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "FMS_cat",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
      ]
    },
    {
      "title": "Final",
      "vod": null,
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "gopher",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "exoticorn",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
       
      ]
    }
  ],
  "staffs": []
}

=== 0b5vr/livecode.demozoo.org/data/2017_shader_showdown_paris_cc_4.json
{
	"title": "Cookie Demoparty / Showdown #4 @ Jardin d'Alice",
	"started": "2017-12-08",
	"date": "8 December 2017",
	"type": "Shader Showdown",
	"vod": "https://youtu.be/ugs3-B3Tng0",
	"software_used": [
        {
          "name": "Bonzomatic",
          "url": "https://github.com/TheNuSan/Bonzomatic/releases/tag/v11",
          "version": "NuSan - v11",
          "purpose": "Graphic"
        }
      ],
	"phases": [{
			"title": "Quarter #1",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": 1,
					"points": null,
					"handle": "Flopine",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/01-flopine.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/01-flopine.jpg"
				},
				{
					"id": null,
					"rank": 2,
					"points": null,
					"handle": "Eybor",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/01-eybor.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/01-eybor.jpg"
				}
			],
			"staffs": [
			]
		},
        {
			"title": "Quarter #2",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": 1,
					"points": null,
					"handle": "Theotime",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/02-theotime.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/02-theotime.jpg"
				},
				{
					"id": null,
					"rank": 2,
					"points": null,
					"handle": "Anton",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/02-anton.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/02-anton.jpg"
				}
			],
			"staffs": [
			]
		},
        {
			"title": "Quarter #3",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": 1,
					"points": null,
					"handle": "XT95",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/03-xt95.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/03-xt95.jpg"
				},
				{
					"id": null,
					"rank": 2,
					"points": null,
					"handle": "Lamogui",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/03-lamogui.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/03-lamogui.jpg"
				}
			],
			"staffs": [
			]
		},
        {
			"title": "Quarter #4",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": 1,
					"points": null,
					"handle": "CoyHot",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/04-coyhot.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/04-coyhot.jpg"
				},
				{
					"id": null,
					"rank": 2,
					"points": null,
					"handle": "Xtrium",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/04-xtrium.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/04-xtrium.jpg"
				}
			],
			"staffs": [
			]
		},
        {
			"title": "Semi #1",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": 1,
					"points": null,
					"handle": "Flopine",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/05-flopine.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/05-flopine.jpg"
				},
				{
					"id": null,
					"rank": 2,
					"points": null,
					"handle": "Theotime",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/05-theotime.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/05-theotime.jpg"
				}
			],
			"staffs": [
			]
		},
        {
			"title": "Semi #2",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": 1,
					"points": null,
					"handle": "XT95",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/06-xt95-xmen-edit.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/06-xt95-xmen-edit.jpg"
				},
				{
					"id": null,
					"rank": 2,
					"points": null,
					"handle": "CoyHot",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/06-coyhot.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/06-coyhot.jpg"
				}
			],
			"staffs": [
			]
		},
        {
			"title": "Final",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": 1,
					"points": null,
					"handle": "XT95",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/07-xt95.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/07-xt95.jpg"
				},
				{
					"id": null,
					"rank": 2,
					"points": null,
					"handle": "Flopine",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/07-flopine.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/07-flopine.jpg"
				}
			],
			"staffs": [
			]
		},
        {
			"title": "Extra",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Extra #1",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/extra-01.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/extra-01.jpg"
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Extra #2",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/extra-02.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/extra-02.jpg"
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Extra #3",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/extra-03.dx9.hlsl",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Extra #4",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/extra-04.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/extra-04.jpg"
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Extra #5",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2017-12-08/extra-05.glsl",
					"shadertoy_url": null,
                    "preview_image": "cc_live_coding_2017-12-08/extra-05.jpg"
				}
			],
			"staffs": [
			]
		}
	],
	"staffs": [{
			"handle": "Cookie Collective",
			"job": "Organizers"
		}
	]
}
