=== 0b5vr/livecode.demozoo.org/meta/event.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "file://./meta/event.schema.json",
  "title": "Event",
  "description": "An event which consist of a set of phases",
  "type": "object",
  "properties": {
    "title": {
      "description": "Name of the Event",
      "type": "string"
    },
    "started": {
      "description": "First day of the event, ISO-8601 format",
      "type": "string"
    },
    "date": {
      "description": "Human readable date",
      "type": "string"
    },
    "type": {
      "description": "Type of event",
      "type": "string"
    },
    "vod": {
      "description": "Link if VOD",
      "type": ["string", "null"]
    },
    "software_used": {
      "description": "Sofware used",
      "type": ["string", "null"]
    },
    "phases": {
      "title": "Phases",
      "description": "All the phases of the event",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Phase",
        "description": "A phase of the event. Consists of multiple entries",
        "properties": {
          "title": {
            "description": "Phase title. Can be null if the event is one phase e.g",
            "type": ["string", "null"]
          },
          "vod": {
            "description": "Link if VOD",
            "type": ["string", "null"]
          },
          "entries": {
            "title": "Entries",
            "description": "All the entry of the phase",
            "type": "array",
            "items": {
              "type": "object",
              "title": "Entry",
              "description": "An entry. Which here consists of a shader creation",
              "properties": {
                "id": {
                  "description": "User Id for the phase (usually for Shader Royale)",
                  "type": ["string", "null"]
                },
                "rank": {
                  "description": "Rank of the entry",
                  "type": ["integer", "null"]
                },
                "points": {
                  "description": "Points of the entry",
                  "type": ["integer", "null"]
                },
                "handle": {
                  "description": "Handle / Username",
                  "type": ["string"]
                },
                "shader_file": {
                  "description": "File of the entry",
                  "type": ["string", "null"]
                },
                "shadertoy_url": {
                  "description": "Shadertoy url",
                  "type": ["string", "null"]
                },
                "vod": {
                  "description": "Link if VOD",
                  "type": ["string", "null"]
                }
              },
              "required": ["handle"]
            }
          },
          "staffs": {
            "description": "Staff info for the phase",
            "type": "array",
            "items": {
              "type": "object",
              "title": "Staff",
              "description": "Staff information. What people were doing",
              "properties": {
                "job": {
                  "description": "Job",
                  "type": "string",
                  "enum": ["Live Music", "Dj Set", "Commentators"]
                },
                "handle": {
                  "description": "Handle / Username",
                  "type": "string"
                }
              },
              "required": ["job", "handle"]
            }
          }
        }
      }
    },
    "staffs": {
      "description": "Staff info for the whole Event",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Staff",
        "description": "Staff information. What people were doing",
        "properties": {
          "job": {
            "description": "Job",
            "type": "string",
            "enum": ["Organizers"]
          },
          "handle": {
            "description": "Handle / Username",
            "type": "string"
          }
        },
        "required": ["job", "handle"]
      }
    }
  },
  "required": ["title", "started", "date", "type"]
}

=== 0b5vr/livecode.demozoo.org/data/2018_shader_showdown_paris_cc_5.json
{
	"title": "Cookie Showdown #5 @ Jardin d'Alice",
	"started": "2018-02-07",
	"date": "07 Feb 2018",
	"type": "Shader Showdown",
	"vod": null,
	"software_used": [
        {
          "name": "Bonzomatic",
          "url": "https://github.com/TheNuSan/Bonzomatic/releases/tag/v11",
          "version": "NuSan - v11",
          "purpose": "Graphic"
        },
		{
			"name": "Veda",
			"url": "https://veda.gl/",
			"version": "",
			"purpose": "Graphic"
		  }
      ],
	"phases": [{
			"title": "",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "XT95",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/01-xt95.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Theotime",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/02-theotime1.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Theotime",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/02-theotime2.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Theotime",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/02-theotime3.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Theotime",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/02-theotime4.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Anton",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/03-anton.glsl",
					"shadertoy_url": null,
					"preview_image":"cc_live_coding_2018-02-07/03-anton.jpg"
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Ponk",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/04-ponk.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/05-elie.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Anton",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/07-anton.frag",
					"shadertoy_url": null,
					"preview_image":"cc_live_coding_2018-02-07/07-anton.jpg"
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "XT95",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/08-xt95.frag",
					"shadertoy_url": null,
					"preview_image":"cc_live_coding_2018-02-07/08-xt95.jpg"
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "wsmind",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-02-07/09-wsmind.glsl",
					"shadertoy_url": null,
					"preview_image":"cc_live_coding_2018-02-07/09-wsmind.jpg"
				}
			],
			"staffs": [
			]
		}
	],
	"staffs": [{
			"handle": "Cookie Collective",
			"job": "Organizers"
		}
	]
}

=== 0b5vr/livecode.demozoo.org/data/2020_shader_showdown_nova.json
{
  "title": "NOVA Online",
  "started": "2020-06-21",
  "date": "21 Jun 2020",
  "type": "Shader Showdown",
  "vod": null,
  "software_used": null,
  "phases": [
    {
      "title": "Round 1",
      "vod": "https://www.youtube.com/watch?v=k_SSkZjlUgE",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "wrighter",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "rc55",
          "job": "Dj Set"
        },
        {
          "handle": "h0ffman",
          "job": "Commentators"
        },
        {
          "handle": "d0pefish",
          "job": "Commentators"
        },
        {
          "handle": "polynomial",
          "job": "Commentators"
        },
        {
          "handle": "rc55",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Round 2",
      "vod": "https://www.youtube.com/watch?v=PF8yuOTqX4k",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "Insomniac",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "LovelyHanibal",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "d0pefish",
          "job": "Dj Set"
        },
        {
          "handle": "h0ffman",
          "job": "Commentators"
        },
        {
          "handle": "d0pefish",
          "job": "Commentators"
        },
        {
          "handle": "polynomial",
          "job": "Commentators"
        },
        {
          "handle": "rc55",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Final",
      "vod": "https://www.youtube.com/watch?v=-n_TnBn01Ew",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "Insomniac",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "lug00ber",
          "job": "Dj Set"
        },
        {
          "handle": "h0ffman",
          "job": "Commentators"
        },
        {
          "handle": "d0pefish",
          "job": "Commentators"
        },
        {
          "handle": "polynomial",
          "job": "Commentators"
        },
        {
          "handle": "rc55",
          "job": "Commentators"
        }
      ]
    }
  ],
  "staffs": []
}

=== 0b5vr/livecode.demozoo.org/data/2018_shader_showdown_paris_cc_6.json
{
	"title": "Cookie Showdown #6 @ Nogozon",
	"started": "2018-03-07",
	"date": "07 Mar 2018",
	"type": "Shader Showdown",
	"vod": null,
	"software_used": [
		{
			"name": "Veda",
			"url": "https://veda.gl/",
			"version": "",
			"purpose": "Graphic"
		  }
      ],
	"phases": [{
			"title": "Round #1",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Anton",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/01-anton.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Lamogui",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/01-lamogui.frag",
					"shadertoy_url": null
				}
			],
			"staffs": [
			]
		},
		{
			"title": "Round #2",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Eybor",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/02-eybor.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Flopine",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/02-flopine.frag",
					"shadertoy_url": null
				}
			],
			"staffs": [
			]
		},
		{
			"title": "Round #3",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/03-elie.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Nicoptere",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/03-nicoptere.frag",
					"shadertoy_url": null
				}
			],
			"staffs": [
			]
		},
		{
			"title": "Round #4",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Anton",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/04-anton.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Leon",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/04-leon.frag",
					"shadertoy_url": null
				}
			],
			"staffs": [
			]
		},
		{
			"title": "Round #5",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Flopine",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/05-flopine.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Mon Blaz",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-03-07/05-monblaz.frag",
					"shadertoy_url": null
				}
			],
			"staffs": [
			]
		}
	],
	"staffs": [{
			"handle": "Cookie Collective",
			"job": "Organizers"
		}
	]
}

=== 0b5vr/livecode.demozoo.org/data/2021_shader_jam_chaos_constructions.json
{
  "title": "Chaos Constructions Winter",
  "started": "2021-02-21",
  "date": "21 Feb 2021",
  "type": "Shader Jam",
  "vod": "https://www.youtube.com/watch?v=vWWlE5sc-WY",
  "software_used": null,
  "phases": [
    {
      "title": null,
      "entries": [
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "cosamental",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "wrighter",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "monsieursoleil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": null,
          "points": null,
          "handle": "provod",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "dipswitch",
          "job": "Dj Set"
        }
      ]
    }
  ],
  "staffs": [
    {
      "handle": "random",
      "job": "Organizers"
    },
    {
      "handle": "havoc",
      "job": "Organizers"
    }
  ]
}

=== 0b5vr/livecode.demozoo.org/data/2020_shader_showdown_solskogen.json
{
  "title": "Solskogen",
  "started": "2020-07-11",
  "date": "11 Jul 2020",
  "type": "Shader Showdown",
  "vod": null,
  "software_used": null,
  "phases": [
    {
      "title": "Qualifier 1",
      "vod": "https://www.youtube.com/watch?v=g9saEPw5Fg",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "tapped",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "phobium",
          "job": "Dj Set"
        },
        {
          "handle": "ferris",
          "job": "Commentators"
        },
        {
          "handle": "Christian",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Qualifier 2",
      "vod": "https://www.youtube.com/watch?v=UWFVrHXz8UI",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "alkama",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "blueberry",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "phobium",
          "job": "Dj Set"
        },
        {
          "handle": "ferris",
          "job": "Commentators"
        },
        {
          "handle": "Christian",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Qualifier 3",
      "vod": "https://www.youtube.com/watch?v=5rjNcG7ioaU",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "blackle",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "wrighter",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "phobium",
          "job": "Dj Set"
        },
        {
          "handle": "ferris",
          "job": "Commentators"
        },
        {
          "handle": "Christian",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Qualifier 4",
      "vod": "https://www.youtube.com/watch?v=7NtxP62lAhE",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "provod",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "rohtie",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "phobium",
          "job": "Dj Set"
        },
        {
          "handle": "ferris",
          "job": "Commentators"
        },
        {
          "handle": "Christian",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Semifinal 1",
      "vod": "https://www.youtube.com/watch?v=gO1V2mCKqOk",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "alkama",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "phobium",
          "job": "Dj Set"
        },
        {
          "handle": "ferris",
          "job": "Commentators"
        },
        {
          "handle": "Christian",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Semifinal 2",
      "vod": "https://www.youtube.com/watch?v=LasL3OGKR_I",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "blackle",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "provod",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "phobium",
          "job": "Dj Set"
        },
        {
          "handle": "ferris",
          "job": "Commentators"
        },
        {
          "handle": "Christian",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Final",
      "vod": "https://www.youtube.com/watch?v=9Nk-cvlonwE",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "evvvvil",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "blackle",
          "shader_file": null,
          "shadertoy_url": null,
          "vod": null
        }
      ],
      "staffs": [
        {
          "handle": "phobium",
          "job": "Dj Set"
        },
        {
          "handle": "ferris",
          "job": "Commentators"
        },
        {
          "handle": "Christian",
          "job": "Commentators"
        }
      ]
    }
  ],
  "staffs": []
}

=== 0b5vr/livecode.demozoo.org/data/2017_shader_showdown_revision.json
{
  "title": "Revision 2017",
  "started": "2017-04-14",
  "date": "14 -17 April 2017",
  "type": "Shader Showdown",
  "vod": null,
  "software_used": null,
  "phases": [
    {
      "title": "Qualifiers #1",
      "vod": "https://www.youtube.com/watch?v=Oa_zCThLXRw",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "fizzer",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "lovely hannibal",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "alkama",
          "job": "Dj Set"
        },
        {
          "handle": "chaos",
          "job": "Commentators"
        },
        {
          "handle": "gopher",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Qualifiers #2",
      "vod": "https://www.youtube.com/watch?v=Oa_zCThLXRw",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "cupe",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "blueberry",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "lug00ber",
          "job": "Dj Set"
        },
        {
          "handle": "chaos",
          "job": "Commentators"
        },
        {
          "handle": "gopher",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Qualifiers #3",
      "vod": "https://www.youtube.com/watch?v=Oa_zCThLXRw",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "eybor",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "ren hoÃ«k",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "ronny",
          "job": "Dj Set"
        },
        {
          "handle": "chaos",
          "job": "Commentators"
        },
        {
          "handle": "gopher",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Qualifiers #4",
      "vod": "https://www.youtube.com/watch?v=Oa_zCThLXRw",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "lj",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "branch",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "lug00ber",
          "job": "Dj Set"
        },
        {
          "handle": "ronny",
          "job": "Dj Set"
        },
        {
          "handle": "ronny",
          "job": "Dj Set"
        },
        {
          "handle": "chaos",
          "job": "Commentators"
        },
        {
          "handle": "gopher",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Semifinals #1",
      "vod": "https://www.youtube.com/watch?v=m6xWreYb3zM",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "cupe",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "fizzer",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "lug00ber",
          "job": "Dj Set"
        },
        {
          "handle": "chaos",
          "job": "Commentators"
        },
        {
          "handle": "gopher",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Semifinals #2",
      "vod": "https://www.youtube.com/watch?v=m6xWreYb3zM",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "lj",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "eybor",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "ronny",
          "job": "Dj Set"
        },
        {
          "handle": "chaos",
          "job": "Commentators"
        },
        {
          "handle": "gopher",
          "job": "Commentators"
        }
      ]
    },
    {
      "title": "Final",
      "vod": "https://www.youtube.com/watch?v=ZwR0zFe57Y4",
      "entries": [
        {
          "id": null,
          "rank": 1,
          "points": null,
          "handle": "lj",
          "shader_file": null,
          "shadertoy_url": null
        },
        {
          "id": null,
          "rank": 2,
          "points": null,
          "handle": "cupe",
          "shader_file": null,
          "shadertoy_url": null
        }
      ],
      "staffs": [
        {
          "handle": "alkama",
          "job": "Dj Set"
        },
        {
          "handle": "chaos",
          "job": "Commentators"
        },
        {
          "handle": "gopher",
          "job": "Commentators"
        }
      ]
    }
    
  ],
  "staffs": []
}

=== 0b5vr/livecode.demozoo.org/data/2018_shader_showdown_paris_cc_7.json
{
	"title": "Laval Virtual 2018 / Cookie Showdown #7",
	"started": "2018-04-07",
	"date": "07 Apr 2018",
	"type": "Shader Showdown",
	"vod": "https://www.youtube.com/watch?v=6ul-jeLTQbM",
	"software_used": [
		{
			"name": "Veda",
			"url": "https://veda.gl/",
			"version": "",
			"purpose": "Graphic"
		  }
      ],
	"phases": [{
			"title": "Exquisite Shader",
			"vod": null,
			"entries": [{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-04-07/01-elie.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Koltes",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-04-07/02-koltes.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-04-07/03-elie.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Elie",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-04-07/04-elie.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Adrian",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-04-07/05-adrian.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"points": null,
					"handle": "Jean Michel",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-04-07/06-jeanmichel.frag",
					"shadertoy_url": null
				},
				{
					"id": null,
					"rank": null,
					"point": null,
					"handle": "Koltes",
					"shader_file": "https://github.com/CookieCollective/Live-Coding-Sources/blob/master/2018-04-07/07-koltes.frag",
					"shadertoy_url": null
				}
			],
			"staffs": [
			]
		}
	],
	"staffs": [{
			"handle": "Cookie Collective",
			"job": "Organizers"
		}
	]
}
